### ISSUE TITLE
Code generation discussion

### ISSUE THREAD

**Issue by falseresync** [AsbestosMC/FabriCreator#6]
Suggestions:
- `javapoet` for algorithms
- templates for everything else

**Comment by falseresync** [comment]
Template example:
```java
package asbestos.fabricreator.%MOD_PACKAGE%;

import net.fabricmc.api.ModInitializer;

public class %MOD_CLASS% implements ModInitializer {
    @Override
    public void onInitialize() {
        %%REGISTRIES%
    }
}
```

**Comment by Ueaj-Kerman** [comment]
I think that can be done via javapoet tbh, it's a bit nicer, but it doesn't really matter

**Comment by Ueaj-Kerman** [comment]
I'll work on the GUI stuff because I'm really bad at it, so it'll add to the crust

**Comment by falseresync** [comment]
Yeah, but that could save quite a bit of effort, especially if only using handlebars approach, aka no logic, only copypasting

**Comment by Ueaj-Kerman** [comment]
ye
